#workflow
#should have name
name: hello

#  on tells when the workflow run 
on:
  workflow_dispatch: 
#jobs
#should be inside the workflows
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - name: say hello to everyone
      run: echo "hello dosto"
        - 


# steps
#should be inside the jobs


#actions
#should be inside the steps
