# what is your Goal of your workflow
name: Auto Linter

on: 
  push: 
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    #this step will automatically clone the code current branch into the runner
    steps:
      - name: Checkout/clone the code
        uses: actions/checkout@v7
        #install linter-
      - name: Install linter
        run: pip install ruff
        #step will install pyhton
      - name: set up python  
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: check file of liting
        run: ruff check .
      
